### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by arbitmcdonald** [ra1nb0rn/cpe_search#1]
When running on Windows 11 with Python 3.10.6 I get the following error:

```
C:\Python\cpe_search-master>python cpe_search.py -q "Steam 2.91" -v 2.3
[+] Running initial setup (might take a couple of minutes)
[+] Downloading NVD's official CPE dictionary (might take some time)
[+] Unzipping dictionary
[+] Creating a custom CPE database for future invocations
Traceback (most recent call last):
  File "C:\Python\cpe_search-master\cpe_search.py", line 541, in <module>
    update(args.version)
  File "C:\Python\cpe_search-master\cpe_search.py", line 81, in update
    content = fin.read()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1599017: character maps to <undefined>
```

This was fixed by changing line 80 in cpe_search.py from:

```
with open(cpe_dict_filepath) as fin:
```

to:

```
with open(cpe_dict_filepath,encoding="utf8") as fin:
```

I can now use your awesome searcher :) 

```
C:\Python\cpe_search-master>python cpe_search.py -q "Steam 2.91" -v 2.3
[+] Running initial setup (might take a couple of minutes)
[+] Downloading NVD's official CPE dictionary (might take some time)
[+] Unzipping dictionary
[+] Creating a custom CPE database for future invocations
[+] Cleaning up
cpe:2.3:a:ponsoftware:explzh:2.91:*:*:*:*:*:*:*
[('cpe:2.3:a:ponsoftware:explzh:2.91:*:*:*:*:*:*:*', 0.42640140575829194),
 ('cpe:2.3:a:valvesoftware:steam_client:-:*:*:*:*:*:*:*', 0.42640140575829194),
 ('cpe:2.3:a:encodable:filechucker:2.91:*:*:*:*:*:*:*', 0.40824812725634746)]
```

**Comment by ra1nb0rn** [comment]
Hi @arbitmcdonald,
thanks for describing this issue and creating a pull request to resolve it :)
